### ISSUE TITLE
Add a function of deleting certain tasks

### ISSUE THREAD

**Issue by tingzhao** [ephemera2015/neutuse#7]
Add an HTTP API for deleting tasks from a certain user:

DELETE http://.../tasks?user=<user_name>&status=<status>

Both user and status should be specified.

**Comment by ephemera2015** [comment]
Http api for deleting tasks has been added as follows,
URL: URL_BASE/api/v1/tasks?{options}
METHOD: DELETE
Query options must include but not limited  to :user, status 
For example:
DELETE  http://127.0.0.1:5000/api/v1/tasks?user=test&status=failed
DELETE  http://127.0.0.1:5000/api/v1/tasks?user=test&status=failed&type=dvid&name=skeletonize
